// Demo fleet + districts, shared by server bootstrap and the standalone
// `npm run seed` script. Single source of truth for first-run data.

import { config } from '../config.js';
import { getDevice, listDevices, upsertDevice, upsertDistrict, type DistrictRow } from './repositories.js';
import { seedHistory } from '../mock/generator.js';
import { DEFAULT_R0_MQ135 } from '../processing/calibration.js';
import type { Device } from '../types.js';

export const DEMO_DEVICES = [
  { id: 'aua-medeu-1', name: 'Медеу-1', lat: 43.161, lng: 77.058, district: 'Медеу (парк)' },
  { id: 'aua-almaly-1', name: 'Алмалы-1', lat: 43.256, lng: 76.929, district: 'Алмалы (центр)' },
  { id: 'aua-alatau-1', name: 'Алатау-1', lat: 43.216, lng: 76.844, district: 'Алатау (жилой)' },
  { id: 'aua-turksib-1', name: 'Турксиб-1', lat: 43.339, lng: 76.985, district: 'Турксиб (промышленный)' },
  { id: 'aua-bostandyk-1', name: 'Бостандык-1', lat: 43.222, lng: 76.919, district: 'Бостандык (жилой)' },
  { id: 'aua-auezov-1', name: 'Ауэзов-1', lat: 43.238, lng: 76.855, district: 'Ауэзов (жилой)' },
];

// District centers are the area-weighted centroid of each district's official
// boundary polygon (see frontend /public/almaty-districts.geojson, sourced from
// OSM administrative boundary relations) — not eyeballed coordinates. Used as
// the reference point for /api/compare-districts and as dropdown/geolocation
// targets on the frontend.
export const DEMO_DISTRICTS: DistrictRow[] = [
  { id: 'alatau', name: 'Алатауский', lat: 43.298736, lng: 76.834789 },
  { id: 'almaly', name: 'Алмалинский', lat: 43.252231, lng: 76.908795 },
  { id: 'auezov', name: 'Ауэзовский', lat: 43.223746, lng: 76.8505 },
  { id: 'bostandyk', name: 'Бостандыкский', lat: 43.155728, lng: 76.923471 },
  { id: 'medeu', name: 'Медеуский', lat: 43.159875, lng: 77.018629 },
  { id: 'nauryzbay', name: 'Наурызбайский', lat: 43.174418, lng: 76.830941 },
  { id: 'turksib', name: 'Турксибский', lat: 43.340927, lng: 76.985681 },
  { id: 'zhetysu', name: 'Жетысуский', lat: 43.308927, lng: 76.924772 },
];

/**
 * The station we actually built and hung: one MQ-135 element on an ESP8266,
 * pushing over MQTT. Registered as a real device (`is_demo: 0`) so it lands on
 * the map, in the station list and in the spatial interpolation next to the
 * development fleet — and so the difference between the two is visible rather
 * than implied.
 */
export function mq135Device(): Device {
  return {
    id: config.mq135DeviceId,
    name: config.mq135DeviceName,
    lat: config.mq135Lat,
    lng: config.mq135Lng,
    district: config.mq135DeviceDistrict,
    sensor_kind: 'mq135',
    is_demo: 0,
    r0_mq2: 10000, r0_mq4: 10000, r0_mq8: 10000, r0_mq135: DEFAULT_R0_MQ135,
    vcc_mv: 3300, rl_ohm: 10000,
    firmware: 'esp8266-mqtt-1.0',
    installed_at: new Date().toISOString(),
    last_seen_at: null,
    active: 1,
  };
}

export function seedDevicesAndDistricts(): void {
  const now = new Date().toISOString();
  for (const d of DEMO_DEVICES) {
    upsertDevice({
      ...d,
      sensor_kind: 'mq_trio',
      // Generated by mock/generator.ts, not measured. The flag travels with the
      // row so every screen can label it instead of passing it off as data.
      is_demo: 1,
      r0_mq2: 10000, r0_mq4: 10000, r0_mq8: 10000, r0_mq135: 10000,
      vcc_mv: 3300, rl_ohm: 10000,
      firmware: 'mock-1.0',
      installed_at: now, last_seen_at: null, active: 1,
    });
  }
  for (const d of DEMO_DISTRICTS) upsertDistrict(d);
}

/**
 * Backfills the `sensor_kind` / `is_demo` flags on databases created before
 * those columns existed. The migration can only give them a default, and the
 * default has to be "real" — so without this every seeded demo device would
 * claim to be physical hardware, and the mock generator (which now only writes
 * to devices flagged demo) would silently stop producing anything.
 */
export function reconcileDeviceFlags(): void {
  const demoIds = new Set(DEMO_DEVICES.map((d) => d.id));
  for (const device of listDevices(false)) {
    const isDemo = demoIds.has(device.id) ? 1 : device.is_demo;
    const kind = device.id === config.mq135DeviceId ? 'mq135' : device.sensor_kind;
    if (isDemo === device.is_demo && kind === device.sensor_kind) continue;
    upsertDevice({ ...device, is_demo: isDemo, sensor_kind: kind });
  }
}

/** Idempotent: called on every boot so the real station survives a reseed. */
export function ensureMq135Device(): void {
  const existing = getDevice(config.mq135DeviceId);
  const device = mq135Device();
  if (!existing) {
    upsertDevice(device);
    return;
  }
  // A calibrated R0 is measured data and must never be clobbered by a restart.
  // A value still sitting at an old default was never calibrated, so it should
  // follow the current default rather than be preserved forever.
  const wasCalibrated = existing.r0_mq135 !== DEFAULT_R0_MQ135 && existing.r0_mq135 !== 10_000;
  upsertDevice({
    ...device,
    installed_at: existing.installed_at,
    r0_mq135: wasCalibrated ? existing.r0_mq135 : DEFAULT_R0_MQ135,
  });
}

// First run only: empty DB → demo fleet (+ history in mock mode).
export function seedIfEmpty(): void {
  if (listDevices(false).length > 0) return;
  seedDevicesAndDistricts();
  if (config.useMock) {
    const r = seedHistory(config.mockSeedDays);
    console.log(`[seed] ${r.insertedProc} history readings across ${DEMO_DEVICES.length} devices`);
  }
}
